'use client';
import Link from 'next/link';
import Image from 'next/image';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Bookmark, ShieldCheck, ArrowUpRight } from 'lucide-react';
import { accountAction, accountState, saveChange, type AccountState } from '@/lib/account/client';
import { readLocal, safeReturn, writeLocal, type SavedItem } from '@/lib/account/model';
import './account.css';
export default function AccountSpace({locale}:{locale:'sr'|'en'}) {
 const en=locale==='en';const [state,setState]=useState<AccountState|null>(null);const [items,setItems]=useState<SavedItem[]>([]);const [local,setLocal]=useState<SavedItem[]>([]);const [tab,setTab]=useState('overview');const [filter,setFilter]=useState('all');const [name,setName]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState('');const [removed,setRemoved]=useState<SavedItem|null>(null);const [returnTo,setReturnTo]=useState(en?'/en/my-umbra':'/moja-umbra');const dialog=useRef<HTMLDialogElement>(null);const cancelDelete=useRef<HTMLButtonElement>(null);const deleteOrigin=useRef<HTMLElement|null>(null);const oldOverflow=useRef('');
 const load=useCallback(async()=>{try{const result=await accountState();setState(result);setName(result.user?.name||'');let guest:SavedItem[]=[];try{guest=readLocal();}catch{setMessage(en?'Browser storage is unavailable.':'Čuvanje u pregledaču nije dostupno.');}setLocal(guest);setItems(result.user?result.items:guest);}catch{setMessage(en?'Could not load your space. Please retry.':'Prostor nije učitan. Pokušajte ponovo.');}},[en]);
 useEffect(()=>{queueMicrotask(()=>void load());window.addEventListener('umbra-saved',load);window.addEventListener('storage',load);queueMicrotask(()=>{const query=new URLSearchParams(location.search);setReturnTo(safeReturn(query.get('returnTo'),en?'/en/my-umbra':'/moja-umbra'));if(query.get('auth')==='failed')setMessage(en?'Sign-in was cancelled or unsuccessful. Please try again.':'Prijava je otkazana ili nije uspela. Pokušajte ponovo.');});return()=>{window.removeEventListener('umbra-saved',load);window.removeEventListener('storage',load);};},[load,en]);
 async function action(body:Record<string,unknown>){setBusy(true);setMessage('');try{const result=await accountAction(body);if(body.action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='moja-umbra.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(body.action==='delete'){dialog.current?.close();}setMessage(body.action==='logout'&&result.revoked===false?(en?'Signed out in this browser. Server revocation could not be confirmed.':'Odjavljeni ste iz ovog pregledača. Opoziv na serveru nije potvrđen.'):(en?'Completed.':'Završeno.'));await load();}catch{setMessage(en?'The action failed. Your changes have not been confirmed. Please retry.':'Radnja nije uspela. Izmene nisu potvrđene. Pokušajte ponovo.');}finally{setBusy(false);}}
 async function transfer(){setBusy(true);try{await accountAction({action:'save',items:local});const transferred=new Set(local.map(item=>item.id));writeLocal(readLocal().filter(item=>!transferred.has(item.id)));setMessage(en?'Your browser items have been transferred.':'Stavke iz pregledača su prenete.');await load();}catch{setMessage(en?'Transfer failed. Your browser items are still available.':'Prenos nije uspeo. Lokalne stavke su sačuvane.');}finally{setBusy(false);}}
 async function removeItem(item:SavedItem){setBusy(true);try{await saveChange(item,true);setRemoved(item);setMessage(en?'Removed. You can undo this action.':'Uklonjeno. Možete poništiti ovu radnju.');await load();}catch{setMessage(en?'Removal failed. Please retry.':'Uklanjanje nije uspelo. Pokušajte ponovo.');}finally{setBusy(false);}}
 async function undoRemoval(){if(!removed)return;setBusy(true);try{await saveChange(removed,false);setRemoved(null);setMessage(en?'Restored.':'Vraćeno.');await load();}catch{setMessage(en?'Could not restore the item. Please retry.':'Stavka nije vraćena. Pokušajte ponovo.');}finally{setBusy(false);}}
 const tabs=[['overview',en?'Overview':'Pregled'],['saved',en?'Saved':'Sačuvano'],['profile',en?'My profile':'Moj profil'],['account',en?'Account & privacy':'Nalog i privatnost']];const kinds=[['all',en?'All':'Sve'],['project',en?'Series':'Serije'],['character',en?'Characters':'Likovi'],['source',en?'Sources':'Izvori'],['blog','Blog']];
 return <main id="main-content" className="u10-account"><div className="u10-account-heading"><p className="u10-eyebrow">UMBRA STUDIO / {en?'YOUR SPACE':'VAŠ PROSTOR'}</p><h1>{en?'My Umbra':'Moja Umbra'}</h1><p>{en?'Keep the stories you want to return to.':'Sačuvajte priče kojima želite da se vratite.'}</p></div><div className="u10-account-grid"><aside className="u10-account-sidebar"><div className="u10-profile-mark"><Image src="/images/v10/umbra-seal.webp" alt="Umbra" width={64} height={64}/></div><p>{state?.user?.name || (state?.user?(en?'Your account':'Vaš nalog'):(en?'Guest':'Gost'))}</p><nav aria-label={en?'Your space':'Vaš prostor'}>{tabs.map(([id,label])=><button key={id} type="button" aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav><small><ShieldCheck size={15}/> {en?'A private space':'Privatan prostor'}</small></aside><section className="u10-account-panel" aria-label={tabs.find(x=>x[0]===tab)?.[1]}>
 {!state&&<p>{en?'Loading your space…':'Učitavanje prostora…'}</p>}
 {tab==='overview'&&<><p className="u10-eyebrow">{en?'WELCOME':'DOBRO DOŠLI'}</p><h2>{en?'Your next story starts here':'Vaša sledeća priča počinje ovde'}</h2><p>{state?.user?(en?'Your saved pages are connected to your account.':'Sačuvane stranice povezane su sa vašim nalogom.'):(en?'You can save pages without an account. They remain only in this browser.':'Stranice možete čuvati i bez naloga. Ostaju samo u ovom pregledaču.')}</p><div className="u10-account-shortcuts"><button onClick={()=>setTab('saved')}><Bookmark/><span>{en?'Open saved pages':'Otvori sačuvane stranice'}</span><ArrowUpRight/></button><Link href={en?'/en/projects':'/serije'}><span>{en?'Explore the series':'Istraži serije'}</span><ArrowUpRight/></Link></div>{items.length>0&&<><h3>{en?'Recently saved':'Poslednje sačuvano'}</h3><ul className="u10-saved-list">{(state?.user?items.slice(0,3):items.slice(-3).reverse()).map(item=><li key={item.id}><Link href={item.href}>{item.title}<ArrowUpRight size={16}/></Link></li>)}</ul></>}</>}
 {tab==='saved'&&<><h2>{en?'Saved pages':'Sačuvane stranice'}</h2><p>{state?.user?(en?'Available on your account.':'Dostupno na vašem nalogu.'):(en?'Stored in this browser. Clearing browser data removes these items.':'Sačuvano u ovom pregledaču. Brisanjem podataka pregledača uklanjate ove stavke.')}</p><div className="u10-account-filters" aria-label={en?'Content type':'Vrsta sadržaja'}>{kinds.map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>{items.filter(x=>filter==='all'||x.kind===filter).length===0?<div className="u10-account-empty"><Bookmark size={30}/><h3>{en?'Room for your discoveries':'Mesto za vaša otkrića'}</h3><p>{en?'Use Save on a series, character or source page.':'Izaberite Sačuvaj na stranici serije, lika ili izvora.'}</p><Link href={en?'/en/projects':'/serije'}>{en?'Explore series':'Istraži serije'} →</Link></div>:<ul className="u10-saved-list">{items.filter(x=>filter==='all'||x.kind===filter).map(item=><li key={item.id}><Link href={item.href}>{item.title}<ArrowUpRight size={16}/></Link><button className="u10-small-button" disabled={busy} onClick={()=>void removeItem(item)}>{en?'Remove':'Ukloni'}</button></li>)}</ul>}</>}
 {tab==='profile'&&<><h2>{en?'My profile':'Moj profil'}</h2>{state?.user?<form onSubmit={event=>{event.preventDefault();void action({action:'profile',name});}}><label htmlFor="umbra-display-name">{en?'Display name':'Prikazano ime'}</label><input id="umbra-display-name" value={name} onChange={e=>setName(e.target.value)} maxLength={60} required autoComplete="nickname"/><p>{en?'Visible only in your private space.':'Vidljivo samo u vašem privatnom prostoru.'}</p><button className="u10-small-button" disabled={busy}>{en?'Save profile':'Sačuvaj profil'}</button></form>:<p>{en?'A profile becomes available after sign-in. Your saved browser items work without one.':'Profil je dostupan nakon prijave. Lokalne sačuvane stavke rade i bez njega.'}</p>}</>}
 {tab==='account'&&<><h2>{en?'Account & privacy':'Nalog i privatnost'}</h2><p>{en?'An account stores your display name and saved pages. Google provides your identity and email. Umbra does not request mailbox access. Chat conversations are not automatically saved to your profile.':'Nalog čuva prikazano ime i sačuvane stranice. Google dostavlja identitet i mejl. Umbra ne traži pristup poštanskom sandučetu. Razgovori sa asistentom ne čuvaju se automatski na profilu.'}</p>{state?.user&&<><dl><dt>{en?'Sign-in provider':'Način prijave'}</dt><dd>Google</dd><dt>{en?'Email':'Mejl'}</dt><dd>{state.user.email}</dd></dl><div className="u10-account-actions"><button disabled={busy} onClick={()=>void action({action:'export'})}>{en?'Export my data':'Izvezi moje podatke'}</button><button disabled={busy} onClick={()=>void action({action:'logout'})}>{en?'Sign out':'Odjavi se'}</button><button disabled={busy} onClick={()=>{setConfirm('');deleteOrigin.current=document.activeElement as HTMLElement;oldOverflow.current=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.showModal();cancelDelete.current?.focus();}}>{en?'Delete account':'Obriši nalog'}</button></div></>}</>}
 {state&&!state.user&&<div className="u10-signin"><h3>{en?'Connect your Umbra space':'Povežite svoj Umbra prostor'}</h3>{state.enabled?<><p>{en?'Continue with Google to create a private profile or sign in to an existing one. Google may ask you to verify your account.':'Nastavite preko Google naloga da kreirate privatni profil ili otvorite postojeći. Google može zatražiti proveru naloga.'}</p><form method="post" action={'/auth/start?returnTo='+encodeURIComponent(returnTo)}><button className="u10-small-button">{en?'Continue with Google':'Nastavi sa Google nalogom'}</button></form></>:<><p>{en?'Account sign-in is not available yet. You can still save pages in this browser.':'Prijava na nalog još nije dostupna. Stranice i dalje možete čuvati u ovom pregledaču.'}</p><button className="u10-small-button" disabled>{en?'Google sign-in unavailable':'Google prijava nije dostupna'}</button></>}</div>}
 {state?.user&&local.length>0&&<div className="u10-signin"><h3>{en?'Bring your saved pages with you':'Prenesite sačuvane stranice'}</h3><p>{en?'Your browser items will be copied to your account. Local items are removed only after the server confirms the transfer.':'Lokalne stavke biće kopirane na nalog. Uklanjaju se iz pregledača tek kada server potvrdi prenos.'}</p><button className="u10-small-button" disabled={busy} onClick={()=>void transfer()}>{en?'Transfer browser items':'Prenesi lokalne stavke'}</button></div>}
 <p role="status" className="u10-account-status">{message}</p>{removed&&<button className="u10-small-button" disabled={busy} onClick={()=>void undoRemoval()}>{en?'Undo removal':'Poništi uklanjanje'}</button>}{!state&&<button className="u10-small-button" onClick={()=>void load()}>{en?'Retry':'Pokušaj ponovo'}</button>}
 </section></div><dialog ref={dialog} className="u10-delete-dialog" onClose={()=>{setConfirm('');document.body.style.overflow=oldOverflow.current;deleteOrigin.current?.focus();}} aria-labelledby="u10-delete-title"><h2 id="u10-delete-title">{en?'Delete your account?':'Obrisati nalog?'}</h2><p>{en?'This permanently removes your Umbra profile and account-saved pages. It does not delete your Google account. Type DELETE MY ACCOUNT to confirm.':'Ovo trajno uklanja Umbra profil i stavke sačuvane na nalogu. Ne briše Google nalog. Za potvrdu unesite DELETE MY ACCOUNT.'}</p><label htmlFor="u10-delete-confirm">{en?'Confirmation':'Potvrda'}</label><input id="u10-delete-confirm" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/><button className="u10-small-button" disabled={busy||confirm!=='DELETE MY ACCOUNT'} onClick={()=>void action({action:'delete',confirm})}>{en?'Permanently delete':'Trajno obriši'}</button><button ref={cancelDelete} className="u10-small-button" onClick={()=>dialog.current?.close()}>{en?'Cancel':'Otkaži'}</button></dialog></main>;
}
