'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Bookmark, Check } from 'lucide-react';
import { readLocal, validItem, type SavedItem } from '@/lib/account/model';
import { accountAction, accountState, saveChange } from '@/lib/account/client';
import './account.css';
export default function SaveButton({item,locale}:{item:SavedItem;locale:'sr'|'en'}) {
 const en=locale==='en';const [saved,setSaved]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [undo,setUndo]=useState(false);const [canConnect,setCanConnect]=useState(false);
 useEffect(()=>{let active=true;const load=async()=>{try{const state=await accountState();let items=state.user?state.items:readLocal();if(active)setCanConnect(state.enabled&&!state.user);if(state.user){const raw=sessionStorage.getItem('umbra-pending-save');if(raw){const pending:unknown=JSON.parse(raw);if(validItem(pending)&&pending.id===item.id){await accountAction({action:'save',items:[pending]});sessionStorage.removeItem('umbra-pending-save');items=[...items,pending];if(active)setMessage(en?'Saved to your account.':'Sačuvano na nalogu.');}}}if(active)setSaved(items.some(x=>x.id===item.id));}catch{if(active)setMessage(en?'Saved items are temporarily unavailable.':'Sačuvane stavke trenutno nisu dostupne.');}};void load();window.addEventListener('umbra-saved',load);window.addEventListener('storage',load);return()=>{active=false;window.removeEventListener('umbra-saved',load);window.removeEventListener('storage',load);};},[item.id,en]);
 async function change(remove:boolean){setBusy(true);try{const place=await saveChange(item,remove);setSaved(!remove);setUndo(remove);setMessage(remove?(en?'Removed.':'Uklonjeno.'):(place==='local'?(en?'Saved in this browser only.':'Sačuvano samo u ovom pregledaču.'):(en?'Saved to your account.':'Sačuvano na nalogu.')));}catch{setMessage(en?'Could not save the change. Please try again.':'Izmena nije sačuvana. Pokušajte ponovo.');}finally{setBusy(false);}}
 return <span className="u10-save"><button type="button" className="u10-small-button" aria-pressed={saved} disabled={busy} onClick={()=>void change(saved)}>{saved?<Check size={16}/>:<Bookmark size={16}/>} {busy?(en?'Saving…':'Čuvanje…'):saved?(en?'Saved':'Sačuvano'):(en?'Save':'Sačuvaj')}</button>{undo&&<button type="button" className="u10-text-button" disabled={busy} onClick={()=>void change(false)}>{en?'Undo':'Poništi'}</button>}{canConnect&&saved&&<Link className="u10-text-button" href={(en?'/en/my-umbra':'/moja-umbra')+'?returnTo='+encodeURIComponent(item.href)} onClick={()=>{try{sessionStorage.setItem('umbra-pending-save',JSON.stringify(item));}catch{setMessage(en?'Sign in, then transfer your saved pages.':'Prijavite se, pa prenesite sačuvane stranice.');}}}>{en?'Save to account':'Sačuvaj na nalogu'}</Link>}<span className="u10-save-status" role="status">{message}</span></span>;
}
