import type { Locale } from "./routes";

export const copy = {
  sr: {
    home: "Početna",
    projects: "Projekti",
    characters: "Likovi",
    latest: "Aktuelno",
    archive: "Arhiva",
    search: "Pretraga",
    blog: "Blog",
    account: "Moja Umbra",
    studio: "Studio",
    watch: "Gledaj",
    explore: "Istraži projekat",
    allProjects: "Svi projekti",
    allCharacters: "Svi likovi",
    dossier: "Otvori dosje",
    back: "Nazad",
    close: "Zatvori",
    menu: "Meni",
    skip: "Pređi na sadržaj",
    independent: "Nezavisan kreativni studio",
    tagline: "Priče koje ostavljaju senku",
    description:
      "Upoznaj projekte MRZIM SVOG BRATA i BIBLIJA, njihove likove i književne izvore.",
    production: "U produkciji",
    development: "U razvoju",
    upcoming: "Uskoro",
    planned: "Planirano",
    published: "Objavljeno",
    completed: "Završeno",
    archived: "Arhivirano",
    project: "Projekat",
    character: "Lik",
    episode: "Epizoda",
    story: "Priča",
    series: "Serija",
    film: "Film",
    main: "Glavni lik",
    supporting: "Sporedni lik",
    source: "Izvorno delo",
    author: "Autor",
    status: "Status",
    format: "Format",
    platform: "Platforma",
    noLatest: "Još nema objava",
    noLatestText:
      "Nove objave, premijere i priče iz studija pojaviće se ovde. U međuvremenu, upoznaj projekte na kojima radimo.",
    noArchive: "Arhiva tek nastaje",
    noArchiveText:
      "Trenutno nema javnih arhivskih zapisa. Projekte i likove možeš istražiti u njihovim odeljcima.",
    query: "Šta želiš da pronađeš?",
    placeholder: "Serija, lik, književni izvor ili članak…",
    noResults: "Nema rezultata za ovu pretragu",
    reset: "Prikaži sve",
    all: "Sve",
    resultCount: "Pronađeno",
    projectFilter: "Filtriraj po projektu",
    roleFilter: "Filtriraj po ulozi",
    episodes: "Epizode",
    plannedNote:
      "Ovo je privremeni pregled epizoda. Naslovi, raspored i obuhvat priče mogu se promeniti; datumi premijera nisu potvrđeni.",
    sameWorld: "Iz istog sveta",
    characterNote: "Dosje lika",
    noPortrait: "Portret nije objavljen",
    read: "Pročitaj izvorno delo",
    downloadSr: "Preuzmi PDF · SR",
    downloadEn: "Preuzmi PDF · EN",
    openSource: "Otvori javni izvor",
    top: "Nazad na vrh",
  },
  en: {
    home: "Home",
    projects: "Projects",
    characters: "Characters",
    latest: "Latest",
    archive: "Archive",
    search: "Search",
    blog: "Blog",
    account: "My Umbra",
    studio: "Studio",
    watch: "Watch",
    explore: "Explore the project",
    allProjects: "All projects",
    allCharacters: "All characters",
    dossier: "Open dossier",
    back: "Back",
    close: "Close",
    menu: "Menu",
    skip: "Skip to content",
    independent: "Independent creative studio",
    tagline: "Stories that leave a shadow",
    description:
      "Explore MRZIM SVOG BRATA and BIBLIJA, their characters and their literary sources.",
    production: "In production",
    development: "In development",
    upcoming: "Coming soon",
    planned: "Planned",
    published: "Published",
    completed: "Completed",
    archived: "Archived",
    project: "Project",
    character: "Character",
    episode: "Episode",
    story: "Story",
    series: "Series",
    film: "Film",
    main: "Main character",
    supporting: "Supporting character",
    source: "Original work",
    author: "Author",
    status: "Status",
    format: "Format",
    platform: "Platform",
    noLatest: "No updates yet",
    noLatestText:
      "New releases, premieres and stories from the studio will appear here. In the meantime, explore the projects we are creating.",
    noArchive: "The archive is taking shape",
    noArchiveText:
      "There are no public archive entries yet. You can explore projects and characters in their own sections.",
    query: "What would you like to find?",
    placeholder: "Series, character, literary source or article…",
    noResults: "No results for this search",
    reset: "Show all",
    all: "All",
    resultCount: "Results",
    projectFilter: "Filter by project",
    roleFilter: "Filter by role",
    episodes: "Episodes",
    plannedNote:
      "This is a provisional episode outline. Titles, order and story coverage may change; premiere dates are not confirmed.",
    sameWorld: "From the same world",
    characterNote: "Character dossier",
    noPortrait: "No published portrait",
    read: "Read the original work",
    downloadSr: "Download PDF · SR",
    downloadEn: "Download PDF · EN",
    openSource: "Open public source",
    top: "Back to top",
  },
} as const;

export function statusLabel(status: string, locale: Locale): string {
  const c = copy[locale];
  const labels: Record<string, string> = {
    "in-production": c.production,
    development: c.development,
    upcoming: c.upcoming,
    planned: c.planned,
    published: c.published,
    completed: c.completed,
    archived: c.archived,
    "in-development": c.development,
    active: c.production,
  };
  return labels[status] ?? c.development;
}
