import type { Locale } from "./routes";

export const copy = {
  sr: {
    home: "Početna",
    projects: "Projekti",
    characters: "Likovi",
    latest: "Aktuelno",
    archive: "Arhiva",
    search: "Pretraga",
    studio: "Studio",
    watch: "Gledaj",
    explore: "Istraži projekat",
    allProjects: "Svi projekti",
    allCharacters: "Svi likovi",
    dossier: "Otvori dosje",
    back: "Nazad",
    close: "Zatvori",
    menu: "Meni",
    skip: "Pređi na sadržaj",
    independent: "Nezavisan kreativni studio",
    tagline: "Priče koje ostavljaju senku.",
    description:
      "Originalne priče, književne ekranizacije i svetovi koji žive kroz film.",
    production: "U produkciji",
    development: "U razvoju",
    upcoming: "Uskoro",
    planned: "Planirano",
    published: "Objavljeno",
    completed: "Završeno",
    archived: "Arhivirano",
    project: "Projekat",
    character: "Lik",
    episode: "Epizoda",
    story: "Priča",
    series: "Serija",
    film: "Film",
    main: "Glavni lik",
    supporting: "Sporedni lik",
    source: "Izvorno delo",
    author: "Autor",
    status: "Status",
    format: "Format",
    platform: "Platforma",
    noLatest: "Sledeći kadar je u pripremi.",
    noLatestText:
      "Nove objave, premijere i priče iz studija pojaviće se ovde. U međuvremenu, upoznaj projekte na kojima radimo.",
    noArchive: "Arhiva tek nastaje.",
    noArchiveText:
      "Ovde će svoje mesto dobiti skice, dokumenti i tragovi nastanka naših svetova.",
    query: "Šta želiš da pronađeš?",
    placeholder: "Projekat, lik ili epizoda…",
    noResults: "Nema rezultata za ovu pretragu.",
    reset: "Prikaži sve",
    all: "Sve",
    resultCount: "Pronađeno",
    projectFilter: "Filtriraj po projektu",
    roleFilter: "Filtriraj po ulozi",
    episodes: "Epizode",
    plannedNote:
      "Epizode su u pripremi. Datumi premijera biće objavljeni kada budu potvrđeni.",
    sameWorld: "Iz istog sveta",
    characterNote: "Dosje lika",
    noPortrait: "Portret u pripremi",
    read: "Pročitaj izvorno delo",
    downloadSr: "Preuzmi PDF · SR",
    downloadEn: "Preuzmi PDF · EN",
    openSource: "Otvori javni izvor",
    top: "Nazad na vrh",
  },
  en: {
    home: "Home",
    projects: "Projects",
    characters: "Characters",
    latest: "Latest",
    archive: "Archive",
    search: "Search",
    studio: "Studio",
    watch: "Watch",
    explore: "Explore the project",
    allProjects: "All projects",
    allCharacters: "All characters",
    dossier: "Open dossier",
    back: "Back",
    close: "Close",
    menu: "Menu",
    skip: "Skip to content",
    independent: "Independent creative studio",
    tagline: "Stories that leave a shadow.",
    description:
      "Original stories, literary adaptations and worlds brought to life through film.",
    production: "In production",
    development: "In development",
    upcoming: "Coming soon",
    planned: "Planned",
    published: "Published",
    completed: "Completed",
    archived: "Archived",
    project: "Project",
    character: "Character",
    episode: "Episode",
    story: "Story",
    series: "Series",
    film: "Film",
    main: "Main character",
    supporting: "Supporting character",
    source: "Original work",
    author: "Author",
    status: "Status",
    format: "Format",
    platform: "Platform",
    noLatest: "The next frame is taking shape.",
    noLatestText:
      "New releases, premieres and stories from the studio will appear here. In the meantime, explore the projects we are creating.",
    noArchive: "The archive is taking shape.",
    noArchiveText:
      "A home for sketches, documents and traces of the worlds we create.",
    query: "What would you like to find?",
    placeholder: "Project, character or episode…",
    noResults: "No results for this search.",
    reset: "Show all",
    all: "All",
    resultCount: "Results",
    projectFilter: "Filter by project",
    roleFilter: "Filter by role",
    episodes: "Episodes",
    plannedNote:
      "Episodes are in preparation. Premiere dates will be announced once confirmed.",
    sameWorld: "From the same world",
    characterNote: "Character dossier",
    noPortrait: "Portrait in preparation",
    read: "Read the original work",
    downloadSr: "Download PDF · SR",
    downloadEn: "Download PDF · EN",
    openSource: "Open public source",
    top: "Back to top",
  },
} as const;

export function statusLabel(status: string, locale: Locale): string {
  const c = copy[locale];
  const labels: Record<string, string> = {
    "in-production": c.production,
    development: c.development,
    upcoming: c.upcoming,
    planned: c.planned,
    published: c.published,
    completed: c.completed,
    archived: c.archived,
    "in-development": c.development,
    active: c.production,
  };
  return labels[status] ?? c.development;
}
